version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "MateusOFCZ"
    reviewers:
      - "MateusOFCZ"
    labels:
      - "Waiting"
